platform:ios, '8.0'
target 'BaseDemo' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'SVProgressHUD', '~> 2.0.3'
  pod 'IQKeyboardManager', '~> 4.0.4'
end

